GUIDES.strawberry = {badge:"KIT 05",hours:1.5,imgs:[1,2,3],L:{
ca:{title:"Bossa maduixa / bossa per mudes",materials:[["Cos de la bossa","2 peces · 65 × 55 cm"],["Peça maduixa","1 peça · 17 × 17 cm"],["Tires","2 tires · 6 × 16 cm"],["Cordonet","50 cm"],["Fre","1 unitat"]],steps:[
 {t:"Calquem el patró",items:["Posa les dues teles encarades.","Calca el patró al revés de la tela.","Retalla les dues capes seguint la línia del patró."],cap:"Pàgina 1 · patró"},
 {t:"Fem la maduixeta",items:["Fes un doble plec als extrems de les tires de 6 cm i fixa’l amb un repunt.","Doblega les tires per la meitat al llarg, cara bonica a fora, i fixa amb zig-zag.","Fes un plec d’1 cm al costat llarg dels triangles.","Col·loca triangle i tira a una punta inferior de cada cos, mirant que coincideixin quan encaris les dues teles."],cap:"Pàgina 1 · maduixeta"},
 {t:"Cosim la bossa",items:["Encara les dues teles, cara bonica amb cara bonica.","Cus laterals i nanses amb repunt i zig-zag.","Col·loca el biaix al voltant de les nanses en dos passos: primer pel revés i després per la cara bonica.","Passa el cordonet per les tires amb una agulla imperdible i afegeix el fre."],cap:"Pàgina 2 · muntatge final"}]},
es:{title:"Bolsa fresa / bolsa para mudas",materials:[["Cuerpo de la bolsa","2 piezas · 65 × 55 cm"],["Pieza fresa","1 pieza · 17 × 17 cm"],["Tiras","2 tiras · 6 × 16 cm"],["Cordón","50 cm"],["Tope","1 unidad"]],steps:[
 {t:"Calcamos el patrón",items:["Enfrenta las dos telas.","Calca el patrón en el revés de la tela.","Recorta las dos capas siguiendo la línea del patrón."],cap:"Página 1 · patrón"},
 {t:"Hacemos la fresita",items:["Haz un doble pliegue en los extremos de las tiras de 6 cm y fíjalo con un pespunte.","Dobla las tiras por la mitad a lo largo, derecho hacia fuera, y fija con zigzag.","Haz un pliegue de 1 cm en el lado largo de los triángulos.","Coloca triángulo y tira en una punta inferior de cada cuerpo, comprobando que coincidan al enfrentar las dos telas."],cap:"Página 1 · fresita"},
 {t:"Cosemos la bolsa",items:["Enfrenta las dos telas, derecho con derecho.","Cose laterales y asas con pespunte y zigzag.","Coloca el bies alrededor de las asas en dos pasos: primero por el revés y después por el derecho.","Pasa el cordón por las tiras con un imperdible y añade el tope."],cap:"Página 2 · montaje final"}]},
en:{title:"Strawberry bag / spare-clothes bag",materials:[["Bag body","2 pieces · 65 × 55 cm"],["Strawberry piece","1 piece · 17 × 17 cm"],["Strips","2 strips · 6 × 16 cm"],["Cord","50 cm"],["Cord stopper","1"]],steps:[
 {t:"Trace the pattern",items:["Put the two fabrics facing each other.","Trace the pattern on the wrong side of the fabric.","Cut both layers following the pattern line."],cap:"Page 1 · pattern"},
 {t:"Make the little strawberry",items:["Double-fold the ends of the 6 cm strips and fix with a line of stitching.","Fold the strips in half lengthwise, right side out, and fix with a zigzag.","Fold 1 cm along the long side of the triangles.","Place triangle and strip at a lower corner of each body so they match when you face the two fabrics."],cap:"Page 1 · strawberry"},
 {t:"Sew the bag",items:["Face the two fabrics, right sides together.","Sew sides and handles with a straight stitch and a zigzag.","Bind the handles in two passes: first from the wrong side, then from the right side.","Thread the cord through the strips with a safety pin and add the stopper."],cap:"Page 2 · final assembly"}]},
de:{title:"Erdbeer-Beutel / Wäschebeutel",materials:[["Beutelkörper","2 Teile · 65 × 55 cm"],["Erdbeerteil","1 Teil · 17 × 17 cm"],["Streifen","2 Streifen · 6 × 16 cm"],["Kordel","50 cm"],["Kordelstopper","1 Stück"]],steps:[
 {t:"Schnitt übertragen",items:["Lege die beiden Stoffe aufeinander.","Übertrage den Schnitt auf die linke Stoffseite.","Schneide beide Lagen entlang der Schnittlinie zu."],cap:"Seite 1 · Schnitt"},
 {t:"Die kleine Erdbeere nähen",items:["Die Enden der 6-cm-Streifen doppelt einschlagen und mit einer Naht fixieren.","Die Streifen der Länge nach falten, rechte Seite aussen, und mit Zickzack fixieren.","An der langen Seite der Dreiecke 1 cm einschlagen.","Dreieck und Streifen an eine untere Ecke jedes Körpers setzen, so dass sie beim Aufeinanderlegen zusammenpassen."],cap:"Seite 1 · Erdbeere"},
 {t:"Beutel nähen",items:["Die beiden Stoffe rechts auf rechts legen.","Seiten und Henkel mit Geradstich und Zickzack nähen.","Die Henkel in zwei Durchgängen einfassen: erst von links, dann von rechts.","Die Kordel mit einer Sicherheitsnadel durch die Streifen ziehen und den Stopper anbringen."],cap:"Seite 2 · Endmontage"}]},
fr:{title:"Sac fraise / sac à rechange",materials:[["Corps du sac","2 pièces · 65 × 55 cm"],["Pièce fraise","1 pièce · 17 × 17 cm"],["Bandes","2 bandes · 6 × 16 cm"],["Cordelette","50 cm"],["Stop-cordon","1"]],steps:[
 {t:"Décalquer le patron",items:["Superpose les deux tissus.","Décalque le patron sur l’envers du tissu.","Découpe les deux épaisseurs en suivant la ligne du patron."],cap:"Page 1 · patron"},
 {t:"Faire la petite fraise",items:["Fais un double repli aux extrémités des bandes de 6 cm et fixe-le d’une piqûre.","Plie les bandes en deux dans la longueur, endroit dehors, et fixe au zigzag.","Fais un repli de 1 cm sur le grand côté des triangles.","Place triangle et bande à un coin inférieur de chaque corps, en vérifiant qu’ils coïncident quand tu superposes les tissus."],cap:"Page 1 · fraise"},
 {t:"Coudre le sac",items:["Superpose les deux tissus endroit contre endroit.","Couds les côtés et les anses au point droit puis au zigzag.","Pose le biais autour des anses en deux temps : d’abord sur l’envers, puis sur l’endroit.","Passe la cordelette dans les bandes avec une épingle à nourrice et ajoute le stop-cordon."],cap:"Page 2 · montage final"}]},
it:{title:"Borsa fragola / sacca per il cambio",materials:[["Corpo della borsa","2 pezzi · 65 × 55 cm"],["Pezzo fragola","1 pezzo · 17 × 17 cm"],["Strisce","2 strisce · 6 × 16 cm"],["Cordoncino","50 cm"],["Fermacorda","1"]],steps:[
 {t:"Ricalchiamo il cartamodello",items:["Affronta i due tessuti.","Ricalca il cartamodello sul rovescio del tessuto.","Taglia i due strati seguendo la linea del cartamodello."],cap:"Pagina 1 · cartamodello"},
 {t:"Facciamo la fragolina",items:["Fai una doppia piega alle estremità delle strisce da 6 cm e fissala con un’impuntura.","Piega le strisce a metà per il lungo, dritto all’esterno, e fissa con zigzag.","Fai una piega di 1 cm sul lato lungo dei triangoli.","Posiziona triangolo e striscia in un angolo inferiore di ogni corpo, controllando che combacino quando affronti i tessuti."],cap:"Pagina 1 · fragolina"},
 {t:"Cuciamo la borsa",items:["Affronta i due tessuti, dritto contro dritto.","Cuci lati e manici con punto dritto e zigzag.","Applica lo sbieco intorno ai manici in due passaggi: prima dal rovescio, poi dal dritto.","Infila il cordoncino nelle strisce con una spilla da balia e aggiungi il fermacorda."],cap:"Pagina 2 · montaggio finale"}]}
}};

GUIDES.shoebag = {badge:"KIT 04b",hours:2,imgs:[1,2,3],L:{
ca:{title:"Bossa de sabates",materials:[["Exterior","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Interior","2 × 18 × 40 cm · 1 × 36 × 40 cm (impermeable)"],["Cremallera","1 unitat · 45 cm"],["Biaix","2 peces · 20 × 4 cm"],["Cinta de motxilla","12 cm"]],steps:[
 {t:"Muntem la cremallera",items:["Col·loca una peça interior de 18 × 40 cm amb la cara bonica amunt.","Alinea la cremallera al costat de 40 cm i posa a sobre la peça exterior, cara bonica cap avall.","Cus amb pota de cremallera, gira les teles i fes un repunt de càrrega.","Repeteix el mateix a l’altre costat de la cremallera."],cap:"Pàgina 1 · cremallera"},
 {t:"Cosim les teles del darrere",items:["Posa la peça amb cremallera sobre la peça interior de 36 × 40 cm, cara bonica amb cara bonica.","A sobre col·loca la peça exterior de 36 × 40 cm, amb les cares boniques encarades.","Cus els dos laterals de 40 cm i remata amb zig-zag.","Gira i centra la cremallera; retalla el sobrant si cal."],cap:"Pàgina 2 · cos principal"},
 {t:"Tanquem i rematem",items:["Centra la cremallera i marca 5 cm de plec a cada lateral.","Fixa els plecs amb agulles i cus el lateral passant per sobre de la cremallera.","Afegeix la tira de 4 cm al marge per fer l’acabat tipus biaix.","Repeteix a l’altre costat, gira la bossa i comprova que els acabats quedin nets."],cap:"Pàgina 3 · tancament"}]},
es:{title:"Bolsa de zapatos",materials:[["Exterior","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Interior","2 × 18 × 40 cm · 1 × 36 × 40 cm (impermeable)"],["Cremallera","1 unidad · 45 cm"],["Bies","2 piezas · 20 × 4 cm"],["Cinta de mochila","12 cm"]],steps:[
 {t:"Montamos la cremallera",items:["Coloca una pieza interior de 18 × 40 cm con el derecho hacia arriba.","Alinea la cremallera en el lado de 40 cm y pon encima la pieza exterior, derecho hacia abajo.","Cose con prensatelas de cremallera, gira las telas y haz un pespunte de carga.","Repite lo mismo al otro lado de la cremallera."],cap:"Página 1 · cremallera"},
 {t:"Cosemos las telas de atrás",items:["Pon la pieza con cremallera sobre la pieza interior de 36 × 40 cm, derecho con derecho.","Encima coloca la pieza exterior de 36 × 40 cm, con los derechos enfrentados.","Cose los dos laterales de 40 cm y remata con zigzag.","Gira y centra la cremallera; recorta el sobrante si hace falta."],cap:"Página 2 · cuerpo principal"},
 {t:"Cerramos y rematamos",items:["Centra la cremallera y marca 5 cm de pliegue en cada lateral.","Fija los pliegues con alfileres y cose el lateral pasando por encima de la cremallera.","Añade la tira de 4 cm al margen para el acabado tipo bies.","Repite al otro lado, gira la bolsa y comprueba que los acabados queden limpios."],cap:"Página 3 · cierre"}]},
en:{title:"Shoe bag",materials:[["Outer","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Lining","2 × 18 × 40 cm · 1 × 36 × 40 cm (waterproof)"],["Zip","1 · 45 cm"],["Binding","2 pieces · 20 × 4 cm"],["Webbing","12 cm"]],steps:[
 {t:"Fit the zip",items:["Place one 18 × 40 cm lining piece right side up.","Align the zip along the 40 cm edge and put the outer piece on top, right side down.","Sew with the zipper foot, turn the fabrics and topstitch.","Repeat on the other side of the zip."],cap:"Page 1 · zip"},
 {t:"Sew the back fabrics",items:["Put the zip piece on the 36 × 40 cm lining piece, right sides together.","On top, place the 36 × 40 cm outer piece, right sides facing.","Sew the two 40 cm sides and finish with a zigzag.","Turn and centre the zip; trim the excess if needed."],cap:"Page 2 · main body"},
 {t:"Close and finish",items:["Centre the zip and mark a 5 cm fold on each side.","Pin the folds and sew the side, passing over the zip.","Add the 4 cm strip to the allowance for a bound finish.","Repeat on the other side, turn the bag and check the finishes are clean."],cap:"Page 3 · closing"}]},
de:{title:"Schuhbeutel",materials:[["Aussenstoff","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Futter","2 × 18 × 40 cm · 1 × 36 × 40 cm (wasserdicht)"],["Reissverschluss","1 Stück · 45 cm"],["Einfassband","2 Teile · 20 × 4 cm"],["Gurtband","12 cm"]],steps:[
 {t:"Reissverschluss einsetzen",items:["Ein Futterteil 18 × 40 cm mit der rechten Seite nach oben legen.","Den Reissverschluss an der 40-cm-Kante ausrichten und das Aussenteil mit der rechten Seite nach unten darauflegen.","Mit dem Reissverschlussfuss nähen, die Stoffe umklappen und absteppen.","Dasselbe auf der anderen Seite des Reissverschlusses wiederholen."],cap:"Seite 1 · Reissverschluss"},
 {t:"Rückseiten nähen",items:["Das Teil mit Reissverschluss rechts auf rechts auf das Futterteil 36 × 40 cm legen.","Darauf das Aussenteil 36 × 40 cm legen, rechte Seiten aufeinander.","Die beiden 40-cm-Seiten nähen und mit Zickzack versäubern.","Wenden und den Reissverschluss zentrieren; Überstand bei Bedarf abschneiden."],cap:"Seite 2 · Hauptteil"},
 {t:"Schliessen und versäubern",items:["Den Reissverschluss zentrieren und an jeder Seite 5 cm Falte anzeichnen.","Die Falten stecken und die Seite über den Reissverschluss hinweg nähen.","Den 4-cm-Streifen an die Nahtzugabe setzen und als Einfassung verarbeiten.","Auf der anderen Seite wiederholen, wenden und prüfen, dass die Kanten sauber sind."],cap:"Seite 3 · Schliessen"}]},
fr:{title:"Sac à chaussures",materials:[["Extérieur","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Doublure","2 × 18 × 40 cm · 1 × 36 × 40 cm (imperméable)"],["Fermeture à glissière","1 · 45 cm"],["Biais","2 pièces · 20 × 4 cm"],["Sangle","12 cm"]],steps:[
 {t:"Poser la fermeture",items:["Pose une pièce de doublure de 18 × 40 cm endroit vers le haut.","Aligne la fermeture sur le côté de 40 cm et pose la pièce extérieure par-dessus, endroit vers le bas.","Couds au pied fermeture, retourne les tissus et surpique.","Répète de l’autre côté de la fermeture."],cap:"Page 1 · fermeture"},
 {t:"Coudre les tissus du dos",items:["Pose la pièce avec fermeture sur la pièce de doublure de 36 × 40 cm, endroit contre endroit.","Par-dessus, place la pièce extérieure de 36 × 40 cm, endroits face à face.","Couds les deux côtés de 40 cm et surfile au zigzag.","Retourne et centre la fermeture ; recoupe l’excédent si besoin."],cap:"Page 2 · corps principal"},
 {t:"Fermer et finir",items:["Centre la fermeture et marque un pli de 5 cm de chaque côté.","Épingle les plis et couds le côté en passant sur la fermeture.","Ajoute la bande de 4 cm sur la marge pour une finition en biais.","Répète de l’autre côté, retourne le sac et vérifie que les finitions sont nettes."],cap:"Page 3 · fermeture"}]},
it:{title:"Sacca per scarpe",materials:[["Esterno","2 × 18 × 40 cm · 1 × 36 × 40 cm"],["Fodera","2 × 18 × 40 cm · 1 × 36 × 40 cm (impermeabile)"],["Cerniera","1 · 45 cm"],["Sbieco","2 pezzi · 20 × 4 cm"],["Fettuccia","12 cm"]],steps:[
 {t:"Montiamo la cerniera",items:["Posiziona un pezzo di fodera 18 × 40 cm con il dritto verso l’alto.","Allinea la cerniera al lato di 40 cm e metti sopra il pezzo esterno, dritto verso il basso.","Cuci con il piedino per cerniere, rivolta i tessuti e fai un’impuntura.","Ripeti sull’altro lato della cerniera."],cap:"Pagina 1 · cerniera"},
 {t:"Cuciamo i tessuti del retro",items:["Metti il pezzo con la cerniera sul pezzo di fodera 36 × 40 cm, dritto contro dritto.","Sopra posiziona il pezzo esterno 36 × 40 cm, con i dritti affrontati.","Cuci i due lati da 40 cm e rifinisci con zigzag.","Rivolta e centra la cerniera; rifila l’eccesso se serve."],cap:"Pagina 2 · corpo principale"},
 {t:"Chiudiamo e rifiniamo",items:["Centra la cerniera e segna 5 cm di piega su ogni lato.","Ferma le pieghe con gli spilli e cuci il lato passando sopra la cerniera.","Aggiungi la striscia da 4 cm al margine per la rifinitura a sbieco.","Ripeti sull’altro lato, rivolta la sacca e controlla che le rifiniture siano pulite."],cap:"Pagina 3 · chiusura"}]}
}};

GUIDES.ruffle = {badge:"KIT 03",hours:4,imgs:[1,2,3,4,5,6],L:{
ca:{title:"Bossa amb volant",materials:[["Nanses","2 tires · 65 × 8 cm + 2 tires d’entretela · 65 cm"],["Tancament","1 tira · aprox. 12 × 4 cm + 1 botó"],["Volant","1,70 m de tela · 10 cm d’ample"],["Exterior","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Folre","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Butxaca","2 × 26 × 42 cm · cremallera 45 cm · cinturilla 45 cm"],["Foam / estabilitzador","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Nanses i tancament",items:["Planxa l’entretela sobre les tires de 8 × 65 cm.","Doblega les tires seguint les marques de l’entretela, amagant els marges a l’interior.","Fes un repunt a cada costat llarg de la nansa.","Prepara la tira de tancament com un biaix i repunta el costat obert."],cap:"Pàgina 1 · nanses i tira de tancament"},
 {t:"Volant",items:["Uneix les tires fins formar un cercle, cara bonica amb cara bonica.","Doblega el cercle per la meitat fins obtenir una banda d’uns 5 cm.","Cus pel costat obert a 1 cm aproximadament.","Posa la tensió a 0 i fil elàstic a la canilla perquè el volant s’arrugui."],cap:"Pàgina 2 · muntatge del volant"},
 {t:"Butxaca amb cremallera",items:["Prepara les peces de 26 × 42 cm, la cremallera, la cinturilla i una peça interior de 36 × 42 cm.","Fes el sandvitx de teles i cremallera i cus amb la pota de cremallera.","Fes un repunt de càrrega molt a prop de la cremallera.","Col·loca la butxaca sobre la peça interior i fixa la cinturilla a la part superior."],cap:"Pàgina 3 · butxaca"},
 {t:"Interior de la bossa",items:["Fixa les peces al foam amb zig-zag als laterals.","Cus el contorn de la peça de 36 × 42 cm amb la peça de 17 × 108 cm.","Afegeix l’altre costat de la bossa.","Deixa una obertura d’uns 10 cm en un lateral per poder girar la bossa."],cap:"Pàgina 4 · interior"},
 {t:"Exterior i volant",items:["Munta l’exterior igual que l’interior, començant per la peça de 17 cm.","Uneix les peces de 6 cm entre elles i remata amb zig-zag.","Reparteix el volant per tota la part superior i fixa’l amb zig-zag.","Col·loca el cercle de 6 cm sobre el volant, fent coincidir les costures, i cus tot el contorn."],cap:"Pàgina 5 · exterior"},
 {t:"Muntatge final",items:["Centra les nanses: marca el centre i situa cada extrem a 6 cm del centre.","Col·loca la tira de tancament al costat de la butxaca.","Posa bossa exterior i interior cara bonica amb cara bonica i cus tot el contorn superior.","Gira pel forat, tanca’l amb punt ocult, fes un repunt superior i cus el botó."],cap:"Pàgina 6 · muntatge final"}]},
es:{title:"Bolso con volante",materials:[["Asas","2 tiras · 65 × 8 cm + 2 tiras de entretela · 65 cm"],["Cierre","1 tira · aprox. 12 × 4 cm + 1 botón"],["Volante","1,70 m de tela · 10 cm de ancho"],["Exterior","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Forro","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Bolsillo","2 × 26 × 42 cm · cremallera 45 cm · pretina 45 cm"],["Foam / estabilizador","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Asas y cierre",items:["Plancha la entretela sobre las tiras de 8 × 65 cm.","Dobla las tiras siguiendo las marcas de la entretela, escondiendo los márgenes dentro.","Haz un pespunte en cada lado largo del asa.","Prepara la tira de cierre como un bies y pespuntea el lado abierto."],cap:"Página 1 · asas y tira de cierre"},
 {t:"Volante",items:["Une las tiras hasta formar un círculo, derecho con derecho.","Dobla el círculo por la mitad hasta obtener una banda de unos 5 cm.","Cose por el lado abierto a 1 cm aproximadamente.","Pon la tensión a 0 e hilo elástico en la canilla para que el volante se frunza."],cap:"Página 2 · montaje del volante"},
 {t:"Bolsillo con cremallera",items:["Prepara las piezas de 26 × 42 cm, la cremallera, la pretina y una pieza interior de 36 × 42 cm.","Haz el sándwich de telas y cremallera y cose con el prensatelas de cremallera.","Haz un pespunte de carga muy cerca de la cremallera.","Coloca el bolsillo sobre la pieza interior y fija la pretina en la parte superior."],cap:"Página 3 · bolsillo"},
 {t:"Interior del bolso",items:["Fija las piezas al foam con zigzag en los laterales.","Cose el contorno de la pieza de 36 × 42 cm con la pieza de 17 × 108 cm.","Añade el otro lado del bolso.","Deja una abertura de unos 10 cm en un lateral para poder girar el bolso."],cap:"Página 4 · interior"},
 {t:"Exterior y volante",items:["Monta el exterior igual que el interior, empezando por la pieza de 17 cm.","Une las piezas de 6 cm entre sí y remata con zigzag.","Reparte el volante por toda la parte superior y fíjalo con zigzag.","Coloca el círculo de 6 cm sobre el volante, haciendo coincidir las costuras, y cose todo el contorno."],cap:"Página 5 · exterior"},
 {t:"Montaje final",items:["Centra las asas: marca el centro y sitúa cada extremo a 6 cm del centro.","Coloca la tira de cierre junto al bolsillo.","Pon bolso exterior e interior derecho con derecho y cose todo el contorno superior.","Gira por el hueco, ciérralo con punto invisible, haz un pespunte superior y cose el botón."],cap:"Página 6 · montaje final"}]},
en:{title:"Ruffle bag",materials:[["Handles","2 strips · 65 × 8 cm + 2 strips of interfacing · 65 cm"],["Closure","1 strip · approx. 12 × 4 cm + 1 button"],["Ruffle","1.70 m of fabric · 10 cm wide"],["Outer","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Lining","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Pocket","2 × 26 × 42 cm · zip 45 cm · waistband tape 45 cm"],["Foam / stabiliser","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Handles and closure",items:["Iron the interfacing onto the 8 × 65 cm strips.","Fold the strips along the interfacing marks, hiding the allowances inside.","Topstitch each long side of the handle.","Prepare the closure strip like binding and topstitch the open side."],cap:"Page 1 · handles and closure strip"},
 {t:"Ruffle",items:["Join the strips into a ring, right sides together.","Fold the ring in half to get a band about 5 cm wide.","Sew along the open edge at about 1 cm.","Set tension to 0 with elastic thread in the bobbin so the ruffle gathers."],cap:"Page 2 · ruffle assembly"},
 {t:"Zip pocket",items:["Prepare the 26 × 42 cm pieces, the zip, the tape and one 36 × 42 cm lining piece.","Make the fabric-and-zip sandwich and sew with the zipper foot.","Topstitch very close to the zip.","Place the pocket on the lining piece and fix the tape along the top."],cap:"Page 3 · pocket"},
 {t:"Bag lining",items:["Fix the pieces to the foam with a zigzag along the sides.","Sew the outline of the 36 × 42 cm piece to the 17 × 108 cm piece.","Add the other side of the bag.","Leave an opening of about 10 cm in one side to turn the bag."],cap:"Page 4 · lining"},
 {t:"Outer and ruffle",items:["Assemble the outer like the lining, starting with the 17 cm piece.","Join the 6 cm pieces to each other and finish with a zigzag.","Spread the ruffle all along the top and fix it with a zigzag.","Place the 6 cm ring over the ruffle, matching the seams, and sew all around."],cap:"Page 5 · outer"},
 {t:"Final assembly",items:["Centre the handles: mark the centre and place each end 6 cm from it.","Place the closure strip next to the pocket.","Put outer and lining bags right sides together and sew all around the top.","Turn through the gap, close it with a slip stitch, topstitch the top and sew on the button."],cap:"Page 6 · final assembly"}]},
de:{title:"Tasche mit Rüsche",materials:[["Henkel","2 Streifen · 65 × 8 cm + 2 Streifen Einlage · 65 cm"],["Verschluss","1 Streifen · ca. 12 × 4 cm + 1 Knopf"],["Rüsche","1,70 m Stoff · 10 cm breit"],["Aussenstoff","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Futter","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Tasche","2 × 26 × 42 cm · Reissverschluss 45 cm · Bundband 45 cm"],["Foam / Stabilisator","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Henkel und Verschluss",items:["Die Einlage auf die Streifen 8 × 65 cm bügeln.","Die Streifen entlang der Einlagemarkierungen falten, die Zugaben nach innen.","Jede lange Seite des Henkels absteppen.","Den Verschlussstreifen wie ein Einfassband vorbereiten und die offene Seite absteppen."],cap:"Seite 1 · Henkel und Verschlussstreifen"},
 {t:"Rüsche",items:["Die Streifen rechts auf rechts zu einem Ring zusammennähen.","Den Ring zur Hälfte falten, sodass ein etwa 5 cm breites Band entsteht.","An der offenen Kante bei etwa 1 cm nähen.","Fadenspannung auf 0 und Gummifaden in die Spule, damit sich die Rüsche kräuselt."],cap:"Seite 2 · Rüsche"},
 {t:"Reissverschlusstasche",items:["Die Teile 26 × 42 cm, den Reissverschluss, das Band und ein Futterteil 36 × 42 cm bereitlegen.","Das Sandwich aus Stoffen und Reissverschluss bilden und mit dem Reissverschlussfuss nähen.","Ganz nah am Reissverschluss absteppen.","Die Tasche auf das Futterteil legen und das Band an der Oberkante fixieren."],cap:"Seite 3 · Tasche"},
 {t:"Innentasche",items:["Die Teile mit Zickzack an den Seiten auf dem Foam fixieren.","Den Umriss des Teils 36 × 42 cm mit dem Teil 17 × 108 cm zusammennähen.","Die andere Seite der Tasche ansetzen.","An einer Seite eine Wendeöffnung von etwa 10 cm lassen."],cap:"Seite 4 · Innen"},
 {t:"Aussen und Rüsche",items:["Das Aussenteil wie das Innenteil zusammensetzen, mit dem 17-cm-Teil beginnen.","Die 6-cm-Teile miteinander verbinden und mit Zickzack versäubern.","Die Rüsche über die ganze Oberkante verteilen und mit Zickzack fixieren.","Den 6-cm-Ring auf die Rüsche legen, Nähte aufeinander, und rundum nähen."],cap:"Seite 5 · Aussen"},
 {t:"Endmontage",items:["Henkel zentrieren: Mitte markieren und jedes Ende 6 cm davon entfernt setzen.","Den Verschlussstreifen neben der Tasche platzieren.","Aussen- und Innentasche rechts auf rechts legen und die Oberkante rundum nähen.","Durch die Öffnung wenden, mit Matratzenstich schliessen, Oberkante absteppen und den Knopf annähen."],cap:"Seite 6 · Endmontage"}]},
fr:{title:"Sac à volant",materials:[["Anses","2 bandes · 65 × 8 cm + 2 bandes d’entoilage · 65 cm"],["Fermeture","1 bande · env. 12 × 4 cm + 1 bouton"],["Volant","1,70 m de tissu · 10 cm de large"],["Extérieur","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Doublure","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Poche","2 × 26 × 42 cm · fermeture 45 cm · ruban 45 cm"],["Mousse / stabilisateur","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Anses et fermeture",items:["Thermocolle l’entoilage sur les bandes de 8 × 65 cm.","Plie les bandes en suivant les repères de l’entoilage, marges cachées à l’intérieur.","Surpique chaque grand côté de l’anse.","Prépare la bande de fermeture comme un biais et surpique le côté ouvert."],cap:"Page 1 · anses et bande de fermeture"},
 {t:"Volant",items:["Assemble les bandes en cercle, endroit contre endroit.","Plie le cercle en deux pour obtenir une bande d’environ 5 cm.","Couds le long du bord ouvert à environ 1 cm.","Tension à 0 et fil élastique dans la canette pour que le volant se fronce."],cap:"Page 2 · montage du volant"},
 {t:"Poche zippée",items:["Prépare les pièces de 26 × 42 cm, la fermeture, le ruban et une pièce de doublure de 36 × 42 cm.","Fais le sandwich tissus + fermeture et couds au pied fermeture.","Surpique très près de la fermeture.","Place la poche sur la pièce de doublure et fixe le ruban en haut."],cap:"Page 3 · poche"},
 {t:"Intérieur du sac",items:["Fixe les pièces sur la mousse au zigzag sur les côtés.","Couds le contour de la pièce de 36 × 42 cm avec la pièce de 17 × 108 cm.","Ajoute l’autre côté du sac.","Laisse une ouverture d’environ 10 cm sur un côté pour retourner le sac."],cap:"Page 4 · intérieur"},
 {t:"Extérieur et volant",items:["Monte l’extérieur comme l’intérieur, en commençant par la pièce de 17 cm.","Assemble les pièces de 6 cm entre elles et surfile au zigzag.","Répartis le volant sur tout le haut et fixe-le au zigzag.","Place le cercle de 6 cm sur le volant, coutures alignées, et couds tout le tour."],cap:"Page 5 · extérieur"},
 {t:"Montage final",items:["Centre les anses : marque le centre et place chaque extrémité à 6 cm.","Place la bande de fermeture à côté de la poche.","Mets sac extérieur et intérieur endroit contre endroit et couds tout le tour du haut.","Retourne par l’ouverture, referme au point invisible, surpique le haut et couds le bouton."],cap:"Page 6 · montage final"}]},
it:{title:"Borsa con balza",materials:[["Manici","2 strisce · 65 × 8 cm + 2 strisce di interfodera · 65 cm"],["Chiusura","1 striscia · circa 12 × 4 cm + 1 bottone"],["Balza","1,70 m di tessuto · 10 cm di altezza"],["Esterno","2 × 30 × 42 cm · 2 × 6 × 42 cm · 1 × 108 × 17 cm · 2 × 6 × 17 cm"],["Fodera","1 × 17 × 108 cm · 2 × 36 × 42 cm"],["Tasca","2 × 26 × 42 cm · cerniera 45 cm · nastro 45 cm"],["Foam / stabilizzatore","2 × 36 × 42 cm · 1 × 17 × 100 cm"]],steps:[
 {t:"Manici e chiusura",items:["Stira l’interfodera sulle strisce da 8 × 65 cm.","Piega le strisce seguendo i segni dell’interfodera, nascondendo i margini all’interno.","Fai un’impuntura su ogni lato lungo del manico.","Prepara la striscia di chiusura come uno sbieco e impuntura il lato aperto."],cap:"Pagina 1 · manici e striscia di chiusura"},
 {t:"Balza",items:["Unisci le strisce fino a formare un anello, dritto contro dritto.","Piega l’anello a metà fino a ottenere una fascia di circa 5 cm.","Cuci lungo il lato aperto a circa 1 cm.","Metti la tensione a 0 e filo elastico nella spolina perché la balza si arricci."],cap:"Pagina 2 · montaggio della balza"},
 {t:"Tasca con cerniera",items:["Prepara i pezzi da 26 × 42 cm, la cerniera, il nastro e un pezzo di fodera da 36 × 42 cm.","Fai il sandwich di tessuti e cerniera e cuci con il piedino per cerniere.","Fai un’impuntura molto vicina alla cerniera.","Posiziona la tasca sul pezzo di fodera e fissa il nastro sul bordo superiore."],cap:"Pagina 3 · tasca"},
 {t:"Interno della borsa",items:["Fissa i pezzi al foam con zigzag sui lati.","Cuci il contorno del pezzo 36 × 42 cm con il pezzo 17 × 108 cm.","Aggiungi l’altro lato della borsa.","Lascia un’apertura di circa 10 cm su un lato per rivoltare la borsa."],cap:"Pagina 4 · interno"},
 {t:"Esterno e balza",items:["Monta l’esterno come l’interno, iniziando dal pezzo da 17 cm.","Unisci i pezzi da 6 cm tra loro e rifinisci con zigzag.","Distribuisci la balza su tutto il bordo superiore e fissala con zigzag.","Posiziona l’anello da 6 cm sopra la balza, facendo combaciare le cuciture, e cuci tutto il contorno."],cap:"Pagina 5 · esterno"},
 {t:"Montaggio finale",items:["Centra i manici: segna il centro e posiziona ogni estremità a 6 cm dal centro.","Posiziona la striscia di chiusura accanto alla tasca.","Metti borsa esterna e interna dritto contro dritto e cuci tutto il bordo superiore.","Rivolta dall’apertura, chiudila con punto invisibile, fai un’impuntura sul bordo e cuci il bottone."],cap:"Pagina 6 · montaggio finale"}]}
}};
