/* ===== Step-by-step guides (the paid part of a kit). Text per language; images in img/guides/<id>/. ===== */
const GUIDES = {};
GUIDES.toiletry = {badge:"KIT 02",hours:3,imgs:[null,1,2,3,4,5],L:{
ca:{title:"Necesser amb volant",intro:"Una guia visual perquè puguis seguir el projecte pas a pas sense perdre’t. Cada bloc t’indica què has de preparar, què has de cosir i com ha de quedar abans de continuar.",pills:["± 3 h","Cremallera · 45 cm","Acolxat + folre","Butxaca interior"],
 materials:[["Volant","2 tires · 70 × 11 cm"],["Exterior","2 peces · 31 × 40 cm"],["Folre interior","2 peces · 31 × 40 cm"],["Butxaca","2 peces · 30 × 12 cm"],["Estabilitzador / foam","2 peces · 31 × 40 cm"],["Cremallera","1 unitat · 45 cm"]],
 steps:[
 {e:"Exterior",t:"Acolxem la tela exterior",items:[["Col·loca","Posa cada peça exterior sobre una peça de foam o estabilitzador."],["Marca","Dibuixa línies verticals cada 5 cm amb un bolígraf de planxa."],["Cus","Cus exactament sobre cada línia perquè tela i estabilitzador quedin units."]],check:"Has de tenir dues peces exteriors acolxades abans de passar al volant."},
 {e:"Volant",t:"Fem el farbalà",items:[["Doblega i planxa","Doblega cada tira de 70 × 11 cm per la meitat, al llarg."],["Prepara la màquina","Posa fil de goma a la canilla. Llargada de puntada: 4. Tensió: 0."],["Arruga","Cus un repunt recte pel costat obert, sense atacar. La tela s’anirà arrugant fins a formar el volant."],["Fixa","Col·loca el volant a la part superior de cada peça acolxada i fixa’l amb un zig-zag."]],tip:"Repeteix aquest procés a les dues peces exteriors.",cap:"Referència · volant"},
 {e:"Folre",t:"Cosim la butxaca",items:[["Enfronta","Posa les dues peces de butxaca cara bonica amb cara bonica."],["Cus","Cus els dos costats llargs a mida de pota."],["Gira i planxa","Gira la peça per un lateral i planxa-la bé."],["Repunta","Fes un repunt a la part superior de la butxaca."],["Col·loca","Centra-la sobre una de les peces de folre i cus només la part inferior."]],cap:"Referència · butxaca"},
 {e:"Muntatge",t:"Muntem la cremallera",items:[["Fes el “sandvitx”","Exterior amb volant + cremallera encarada al volant + folre encarat a l’exterior."],["Fixa","Alinia les tres capes a la part superior i subjecta-les amb agulles."],["Cus","Utilitza la pota de cremallera i cus la part superior del conjunt."],["Gira i repunta","Obre les teles cap a fora, estira-les bé i fes un repunt de càrrega per sota del volant."],["Repeteix","Fes exactament el mateix a l’altre costat de la cremallera."]],warn:"El repunt ha de tapar els fils que han fixat el volant a la tela exterior. Si encara es veuen, entra una mica més el repunt.",cap:"Referència · cremallera"},
 {e:"Tancament",t:"Tanquem el necesser",items:[["Enfronta","Posa juntes les dues cares exteriors i, per separat, les dues cares interiors, sempre cara bonica amb cara bonica."],["Cus els laterals llargs","Fes un repunt recte i un zig-zag als costats llargs."],["Gira","Gira el necesser perquè el folre quedi a l’exterior."],["Centra la cremallera","Col·loca la cremallera al centre i cus els dos extrems curts."],["Acaba els extrems","Utilitza les tires de 4,5 cm com a biaix: cus a 1 cm, fes doble plec i tanca per la part posterior."]],cap:"Referència · tancament"},
 {e:"Volum",t:"Li donem forma",items:[["Forma les cantonades","Triangula les quatre cantonades."],["Mesura","Marca una línia d’11 cm d’amplada, que correspon a 5,5 cm d’alçada."],["Cus","Cus directament sobre la línia marcada."],["Retalla","Retalla el sobrant deixant 1 cm de marge."],["Acaba","Torna a utilitzar les tires de 4,5 cm com a biaix perquè els costats quedin ben nets."]],warn:"Abans de cosir, comprova que les teles, especialment el folre, estiguin ben planes i sense plecs. Obrir la cremallera et pot ajudar.",cap:"Referència · cantonades"}],
 outro:"Necesser acabat. Guarda aquestes instruccions amb el teu kit i revisa el “check” del pas anterior si algun pas et genera dubtes."},
es:{title:"Neceser con volante",intro:"Una guía visual para seguir el proyecto paso a paso sin perderte. Cada bloque te indica qué preparar, qué coser y cómo debe quedar antes de continuar.",pills:["± 3 h","Cremallera · 45 cm","Acolchado + forro","Bolsillo interior"],
 materials:[["Volante","2 tiras · 70 × 11 cm"],["Exterior","2 piezas · 31 × 40 cm"],["Forro interior","2 piezas · 31 × 40 cm"],["Bolsillo","2 piezas · 30 × 12 cm"],["Estabilizador / foam","2 piezas · 31 × 40 cm"],["Cremallera","1 unidad · 45 cm"]],
 steps:[
 {e:"Exterior",t:"Acolchamos la tela exterior",items:[["Coloca","Pon cada pieza exterior sobre una pieza de foam o estabilizador."],["Marca","Dibuja líneas verticales cada 5 cm con un bolígrafo de plancha."],["Cose","Cose exactamente sobre cada línea para unir tela y estabilizador."]],check:"Debes tener dos piezas exteriores acolchadas antes de pasar al volante."},
 {e:"Volante",t:"Hacemos el volante",items:[["Dobla y plancha","Dobla cada tira de 70 × 11 cm por la mitad, a lo largo."],["Prepara la máquina","Pon hilo elástico en la canilla. Largo de puntada: 4. Tensión: 0."],["Frunce","Cose un pespunte recto por el lado abierto, sin rematar. La tela se irá frunciendo hasta formar el volante."],["Fija","Coloca el volante en la parte superior de cada pieza acolchada y fíjalo con un zigzag."]],tip:"Repite este proceso en las dos piezas exteriores.",cap:"Referencia · volante"},
 {e:"Forro",t:"Cosemos el bolsillo",items:[["Enfrenta","Pon las dos piezas de bolsillo derecho con derecho."],["Cose","Cose los dos lados largos a medida de prensatelas."],["Gira y plancha","Gira la pieza por un lateral y plánchala bien."],["Pespuntea","Haz un pespunte en la parte superior del bolsillo."],["Coloca","Céntralo sobre una de las piezas de forro y cose solo la parte inferior."]],cap:"Referencia · bolsillo"},
 {e:"Montaje",t:"Montamos la cremallera",items:[["Haz el “sándwich”","Exterior con volante + cremallera encarada al volante + forro encarado al exterior."],["Fija","Alinea las tres capas por la parte superior y sujétalas con alfileres."],["Cose","Usa el prensatelas de cremallera y cose la parte superior del conjunto."],["Gira y pespuntea","Abre las telas hacia fuera, estíralas bien y haz un pespunte de carga por debajo del volante."],["Repite","Haz exactamente lo mismo al otro lado de la cremallera."]],warn:"El pespunte debe tapar los hilos que fijaron el volante a la tela exterior. Si aún se ven, mete un poco más el pespunte.",cap:"Referencia · cremallera"},
 {e:"Cierre",t:"Cerramos el neceser",items:[["Enfrenta","Junta las dos caras exteriores y, por separado, las dos interiores, siempre derecho con derecho."],["Cose los laterales largos","Haz un pespunte recto y un zigzag en los lados largos."],["Gira","Gira el neceser para que el forro quede por fuera."],["Centra la cremallera","Coloca la cremallera en el centro y cose los dos extremos cortos."],["Remata los extremos","Usa las tiras de 4,5 cm como bies: cose a 1 cm, haz doble pliegue y cierra por la parte trasera."]],cap:"Referencia · cierre"},
 {e:"Volumen",t:"Le damos forma",items:[["Forma las esquinas","Triangula las cuatro esquinas."],["Mide","Marca una línea de 11 cm de ancho, que corresponde a 5,5 cm de alto."],["Cose","Cose directamente sobre la línea marcada."],["Recorta","Recorta el sobrante dejando 1 cm de margen."],["Remata","Vuelve a usar las tiras de 4,5 cm como bies para que los lados queden limpios."]],warn:"Antes de coser, comprueba que las telas, sobre todo el forro, estén bien planas y sin pliegues. Abrir la cremallera ayuda.",cap:"Referencia · esquinas"}],
 outro:"Neceser terminado. Guarda estas instrucciones con tu kit y revisa el “check” del paso anterior si alguno te genera dudas."},
en:{title:"Ruffle toiletry bag",intro:"A visual guide so you can follow the project step by step without getting lost. Each block tells you what to prepare, what to sew and what it should look like before you carry on.",pills:["± 3 h","Zip · 45 cm","Quilted + lined","Inner pocket"],
 materials:[["Ruffle","2 strips · 70 × 11 cm"],["Outer","2 pieces · 31 × 40 cm"],["Lining","2 pieces · 31 × 40 cm"],["Pocket","2 pieces · 30 × 12 cm"],["Stabiliser / foam","2 pieces · 31 × 40 cm"],["Zip","1 · 45 cm"]],
 steps:[
 {e:"Outer",t:"Quilt the outer fabric",items:[["Place","Lay each outer piece on a piece of foam or stabiliser."],["Mark","Draw vertical lines every 5 cm with a heat-erasable pen."],["Sew","Sew exactly on each line so fabric and stabiliser are joined."]],check:"You should have two quilted outer pieces before moving on to the ruffle."},
 {e:"Ruffle",t:"Make the ruffle",items:[["Fold and press","Fold each 70 × 11 cm strip in half lengthwise."],["Set up the machine","Put elastic thread in the bobbin. Stitch length: 4. Tension: 0."],["Gather","Sew a straight line along the open edge, without backstitching. The fabric will gather itself into a ruffle."],["Attach","Place the ruffle along the top of each quilted piece and fix it with a zigzag."]],tip:"Repeat this on both outer pieces.",cap:"Reference · ruffle"},
 {e:"Lining",t:"Sew the pocket",items:[["Face","Put the two pocket pieces right sides together."],["Sew","Sew the two long sides at foot width."],["Turn and press","Turn the piece through one side and press it well."],["Topstitch","Topstitch the upper edge of the pocket."],["Place","Centre it on one lining piece and sew only the bottom edge."]],cap:"Reference · pocket"},
 {e:"Assembly",t:"Fit the zip",items:[["Make the “sandwich”","Outer with ruffle + zip facing the ruffle + lining facing the outer."],["Pin","Align the three layers along the top and pin them."],["Sew","Use the zipper foot and sew the top of the set."],["Turn and topstitch","Open the fabrics outwards, pull them flat and topstitch just below the ruffle."],["Repeat","Do exactly the same on the other side of the zip."]],warn:"The topstitch must cover the threads that fixed the ruffle to the outer fabric. If they still show, move the topstitch in a little.",cap:"Reference · zip"},
 {e:"Closing",t:"Close the bag",items:[["Face","Put the two outer sides together and, separately, the two lining sides, always right sides together."],["Sew the long sides","Sew a straight line and a zigzag along the long sides."],["Turn","Turn the bag so the lining is on the outside."],["Centre the zip","Place the zip in the middle and sew the two short ends."],["Finish the ends","Use the 4.5 cm strips as binding: sew at 1 cm, double fold and close on the back."]],cap:"Reference · closing"},
 {e:"Volume",t:"Give it shape",items:[["Form the corners","Box the four corners."],["Measure","Mark a line 11 cm wide, which gives 5.5 cm of height."],["Sew","Sew directly on the marked line."],["Trim","Trim the excess leaving a 1 cm allowance."],["Finish","Use the 4.5 cm strips again as binding so the sides are clean."]],warn:"Before sewing, check that the fabrics, especially the lining, are flat and without folds. Opening the zip helps.",cap:"Reference · corners"}],
 outro:"Toiletry bag done. Keep these instructions with your kit and go back to the previous “check” if a step raises doubts."},
de:{title:"Necessaire mit Rüsche",intro:"Eine visuelle Anleitung, damit du das Projekt Schritt für Schritt nachvollziehen kannst. Jeder Block sagt dir, was du vorbereitest, was du nähst und wie es aussehen soll, bevor es weitergeht.",pills:["± 3 h","Reissverschluss · 45 cm","Gesteppt + gefüttert","Innentasche"],
 materials:[["Rüsche","2 Streifen · 70 × 11 cm"],["Aussenstoff","2 Teile · 31 × 40 cm"],["Futter","2 Teile · 31 × 40 cm"],["Tasche","2 Teile · 30 × 12 cm"],["Stabilisator / Foam","2 Teile · 31 × 40 cm"],["Reissverschluss","1 Stück · 45 cm"]],
 steps:[
 {e:"Aussenstoff",t:"Aussenstoff steppen",items:[["Auflegen","Lege jedes Aussenteil auf ein Stück Foam oder Stabilisator."],["Anzeichnen","Zeichne mit einem Bügelstift alle 5 cm senkrechte Linien."],["Nähen","Nähe genau auf jeder Linie, damit Stoff und Stabilisator verbunden sind."]],check:"Du brauchst zwei gesteppte Aussenteile, bevor es mit der Rüsche weitergeht."},
 {e:"Rüsche",t:"Rüsche nähen",items:[["Falten und bügeln","Falte jeden Streifen von 70 × 11 cm der Länge nach zur Hälfte."],["Maschine einstellen","Gummifaden in die Spule. Stichlänge: 4. Fadenspannung: 0."],["Kräuseln","Nähe eine gerade Naht an der offenen Kante, ohne zu verriegeln. Der Stoff kräuselt sich zur Rüsche."],["Fixieren","Lege die Rüsche an die Oberkante jedes gesteppten Teils und fixiere sie mit Zickzack."]],tip:"Wiederhole das an beiden Aussenteilen.",cap:"Referenz · Rüsche"},
 {e:"Futter",t:"Tasche nähen",items:[["Aufeinanderlegen","Lege die beiden Taschenteile rechts auf rechts."],["Nähen","Nähe die beiden langen Seiten füsschenbreit."],["Wenden und bügeln","Wende das Teil durch eine Seite und bügle es gut."],["Absteppen","Steppe die Oberkante der Tasche ab."],["Platzieren","Zentriere sie auf einem Futterteil und nähe nur die Unterkante fest."]],cap:"Referenz · Tasche"},
 {e:"Montage",t:"Reissverschluss einsetzen",items:[["Das „Sandwich“ bauen","Aussenteil mit Rüsche + Reissverschluss zur Rüsche gewandt + Futter zum Aussenteil gewandt."],["Stecken","Richte die drei Lagen an der Oberkante aus und stecke sie."],["Nähen","Nähe mit dem Reissverschlussfuss die Oberkante des Pakets."],["Wenden und absteppen","Klappe die Stoffe nach aussen, ziehe sie glatt und steppe knapp unter der Rüsche ab."],["Wiederholen","Mache genau dasselbe auf der anderen Seite des Reissverschlusses."]],warn:"Die Absteppnaht muss die Fäden verdecken, mit denen die Rüsche fixiert wurde. Sieht man sie noch, setze die Naht etwas weiter innen.",cap:"Referenz · Reissverschluss"},
 {e:"Schliessen",t:"Necessaire schliessen",items:[["Aufeinanderlegen","Lege die beiden Aussenseiten aufeinander und getrennt davon die beiden Futterseiten, immer rechts auf rechts."],["Lange Seiten nähen","Nähe die langen Seiten mit Geradstich und Zickzack."],["Wenden","Wende das Necessaire, sodass das Futter aussen liegt."],["Reissverschluss zentrieren","Lege den Reissverschluss in die Mitte und nähe die beiden kurzen Enden."],["Enden versäubern","Nutze die 4,5-cm-Streifen als Einfassband: bei 1 cm nähen, doppelt falten und auf der Rückseite schliessen."]],cap:"Referenz · Schliessen"},
 {e:"Volumen",t:"Form geben",items:[["Ecken formen","Falte die vier Ecken zu Dreiecken."],["Messen","Zeichne eine 11 cm breite Linie an; das ergibt 5,5 cm Höhe."],["Nähen","Nähe direkt auf der angezeichneten Linie."],["Zurückschneiden","Schneide den Überstand auf 1 cm Nahtzugabe zurück."],["Versäubern","Nutze wieder die 4,5-cm-Streifen als Einfassband, damit die Seiten sauber sind."]],warn:"Prüfe vor dem Nähen, dass die Stoffe, vor allem das Futter, glatt und ohne Falten liegen. Den Reissverschluss zu öffnen hilft.",cap:"Referenz · Ecken"}],
 outro:"Necessaire fertig. Bewahre diese Anleitung beim Kit auf und schau beim „Check“ des vorherigen Schritts nach, wenn etwas unklar ist."},
fr:{title:"Trousse à volant",intro:"Un guide visuel pour suivre le projet pas à pas sans te perdre. Chaque bloc t’indique quoi préparer, quoi coudre et à quoi ça doit ressembler avant de continuer.",pills:["± 3 h","Fermeture · 45 cm","Matelassé + doublé","Poche intérieure"],
 materials:[["Volant","2 bandes · 70 × 11 cm"],["Extérieur","2 pièces · 31 × 40 cm"],["Doublure","2 pièces · 31 × 40 cm"],["Poche","2 pièces · 30 × 12 cm"],["Stabilisateur / mousse","2 pièces · 31 × 40 cm"],["Fermeture à glissière","1 · 45 cm"]],
 steps:[
 {e:"Extérieur",t:"Matelasser le tissu extérieur",items:[["Place","Pose chaque pièce extérieure sur une pièce de mousse ou de stabilisateur."],["Trace","Trace des lignes verticales tous les 5 cm au stylo effaçable à la chaleur."],["Couds","Couds exactement sur chaque ligne pour solidariser tissu et stabilisateur."]],check:"Tu dois avoir deux pièces extérieures matelassées avant de passer au volant."},
 {e:"Volant",t:"Faire le volant",items:[["Plie et repasse","Plie chaque bande de 70 × 11 cm en deux dans la longueur."],["Prépare la machine","Fil élastique dans la canette. Longueur de point : 4. Tension : 0."],["Fronce","Pique une ligne droite le long du bord ouvert, sans point d’arrêt. Le tissu se fronce tout seul en volant."],["Fixe","Place le volant en haut de chaque pièce matelassée et fixe-le au zigzag."]],tip:"Répète l’opération sur les deux pièces extérieures.",cap:"Référence · volant"},
 {e:"Doublure",t:"Coudre la poche",items:[["Superpose","Place les deux pièces de poche endroit contre endroit."],["Couds","Couds les deux grands côtés au bord du pied."],["Retourne et repasse","Retourne la pièce par un côté et repasse-la bien."],["Surpique","Surpique le haut de la poche."],["Place","Centre-la sur une pièce de doublure et ne couds que le bas."]],cap:"Référence · poche"},
 {e:"Montage",t:"Poser la fermeture",items:[["Fais le « sandwich »","Extérieur avec volant + fermeture face au volant + doublure face à l’extérieur."],["Épingle","Aligne les trois épaisseurs en haut et épingle."],["Couds","Utilise le pied fermeture et couds le haut de l’ensemble."],["Retourne et surpique","Ouvre les tissus vers l’extérieur, tends-les bien et surpique juste sous le volant."],["Répète","Fais exactement la même chose de l’autre côté de la fermeture."]],warn:"La surpiqûre doit couvrir les fils qui ont fixé le volant au tissu extérieur. S’ils dépassent, rentre un peu la surpiqûre.",cap:"Référence · fermeture"},
 {e:"Fermeture",t:"Fermer la trousse",items:[["Superpose","Assemble les deux faces extérieures et, séparément, les deux faces intérieures, toujours endroit contre endroit."],["Couds les grands côtés","Une ligne droite puis un zigzag sur les grands côtés."],["Retourne","Retourne la trousse pour que la doublure soit à l’extérieur."],["Centre la fermeture","Place la fermeture au centre et couds les deux petits côtés."],["Finis les extrémités","Utilise les bandes de 4,5 cm comme biais : couds à 1 cm, double pli et referme au dos."]],cap:"Référence · fermeture"},
 {e:"Volume",t:"Donner la forme",items:[["Forme les coins","Triangule les quatre coins."],["Mesure","Trace une ligne de 11 cm de large, soit 5,5 cm de hauteur."],["Couds","Couds directement sur la ligne tracée."],["Recoupe","Recoupe l’excédent en laissant 1 cm de marge."],["Finis","Réutilise les bandes de 4,5 cm comme biais pour des côtés bien nets."]],warn:"Avant de coudre, vérifie que les tissus, surtout la doublure, sont bien à plat et sans plis. Ouvrir la fermeture aide.",cap:"Référence · coins"}],
 outro:"Trousse terminée. Garde ces instructions avec ton kit et reviens au « check » de l’étape précédente en cas de doute."},
it:{title:"Beauty case con balza",intro:"Una guida visiva per seguire il progetto passo dopo passo senza perderti. Ogni blocco ti dice cosa preparare, cosa cucire e come deve risultare prima di continuare.",pills:["± 3 h","Cerniera · 45 cm","Trapuntato + foderato","Tasca interna"],
 materials:[["Balza","2 strisce · 70 × 11 cm"],["Esterno","2 pezzi · 31 × 40 cm"],["Fodera","2 pezzi · 31 × 40 cm"],["Tasca","2 pezzi · 30 × 12 cm"],["Stabilizzatore / foam","2 pezzi · 31 × 40 cm"],["Cerniera","1 · 45 cm"]],
 steps:[
 {e:"Esterno",t:"Trapuntiamo il tessuto esterno",items:[["Posiziona","Metti ogni pezzo esterno su un pezzo di foam o stabilizzatore."],["Segna","Traccia linee verticali ogni 5 cm con una penna cancellabile col ferro."],["Cuci","Cuci esattamente su ogni linea per unire tessuto e stabilizzatore."]],check:"Devi avere due pezzi esterni trapuntati prima di passare alla balza."},
 {e:"Balza",t:"Facciamo la balza",items:[["Piega e stira","Piega ogni striscia di 70 × 11 cm a metà per il lungo."],["Prepara la macchina","Filo elastico nella spolina. Lunghezza punto: 4. Tensione: 0."],["Arriccia","Cuci una linea dritta sul lato aperto, senza fermare. Il tessuto si arriccia da solo formando la balza."],["Fissa","Posiziona la balza sul bordo superiore di ogni pezzo trapuntato e fissala con uno zigzag."]],tip:"Ripeti su entrambi i pezzi esterni.",cap:"Riferimento · balza"},
 {e:"Fodera",t:"Cuciamo la tasca",items:[["Affronta","Metti i due pezzi della tasca dritto contro dritto."],["Cuci","Cuci i due lati lunghi a larghezza di piedino."],["Rivolta e stira","Rivolta il pezzo da un lato e stiralo bene."],["Impuntura","Fai un’impuntura sul bordo superiore della tasca."],["Posiziona","Centrala su un pezzo di fodera e cuci solo il bordo inferiore."]],cap:"Riferimento · tasca"},
 {e:"Montaggio",t:"Montiamo la cerniera",items:[["Fai il “sandwich”","Esterno con balza + cerniera rivolta verso la balza + fodera rivolta verso l’esterno."],["Fissa","Allinea i tre strati sul bordo superiore e fermali con gli spilli."],["Cuci","Usa il piedino per cerniere e cuci il bordo superiore dell’insieme."],["Rivolta e impuntura","Apri i tessuti verso l’esterno, tendili bene e fai un’impuntura appena sotto la balza."],["Ripeti","Fai esattamente lo stesso sull’altro lato della cerniera."]],warn:"L’impuntura deve coprire i fili che hanno fissato la balza al tessuto esterno. Se si vedono ancora, sposta l’impuntura un po’ più dentro.",cap:"Riferimento · cerniera"},
 {e:"Chiusura",t:"Chiudiamo il beauty case",items:[["Affronta","Unisci le due facce esterne e, separatamente, le due interne, sempre dritto contro dritto."],["Cuci i lati lunghi","Una cucitura dritta e uno zigzag sui lati lunghi."],["Rivolta","Rivolta il beauty case in modo che la fodera resti all’esterno."],["Centra la cerniera","Metti la cerniera al centro e cuci le due estremità corte."],["Rifinisci le estremità","Usa le strisce da 4,5 cm come sbieco: cuci a 1 cm, doppia piega e chiudi sul retro."]],cap:"Riferimento · chiusura"},
 {e:"Volume",t:"Diamo la forma",items:[["Forma gli angoli","Triangola i quattro angoli."],["Misura","Segna una linea larga 11 cm, che corrisponde a 5,5 cm di altezza."],["Cuci","Cuci direttamente sulla linea segnata."],["Rifila","Rifila l’eccesso lasciando 1 cm di margine."],["Rifinisci","Usa di nuovo le strisce da 4,5 cm come sbieco per lati puliti."]],warn:"Prima di cucire, controlla che i tessuti, soprattutto la fodera, siano ben piatti e senza pieghe. Aprire la cerniera aiuta.",cap:"Riferimento · angoli"}],
 outro:"Beauty case finito. Conserva queste istruzioni con il kit e rileggi il “check” del passo precedente se qualcosa non ti torna."}
}};

GUIDES.basic = {badge:"KIT 06",hours:2,imgs:[1,2,3],L:{
ca:{title:"Bossa amb base",materials:[["Interior","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Exterior","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Nanses","2 tires · 37 × 8 cm"]],steps:[
 {t:"Donem forma a les dues bosses",items:["Sobre una peça de 37 × 37 cm, alinea la tira de 15 × 108 cm a tres costats, cara bonica amb cara bonica.","Cus a 1 cm i remata amb zig-zag.","Afegeix l’altra peça de 37 × 37 cm.","Repeteix amb el folre, deixant un forat en un lateral per girar la bossa."],cap:"Pàgina 1 · cos de la bossa"},
 {t:"Fem les nanses",items:["Doblega cada tira per la meitat, amb la cara bonica a dins.","Cus el costat llarg i un costat curt.","Gira, planxa i fes un repunt de càrrega als dos costats llargs.","Marca el centre de la peça i situa les nanses a 5 cm a cada costat del centre."],cap:"Pàgina 2 · nanses"},
 {t:"Muntem la bossa",items:["Posa la bossa exterior dins la bossa interior, amb les cares boniques encarades.","Fes coincidir les costures i cus tot el contorn superior a 1 cm.","Gira pel forat del folre i tanca’l amb punt amagat.","Planxa i fes un repunt de càrrega a tot el contorn superior."],cap:"Pàgina 2–3 · muntatge"}]},
es:{title:"Bolso con base",materials:[["Interior","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Exterior","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Asas","2 tiras · 37 × 8 cm"]],steps:[
 {t:"Damos forma a las dos bolsas",items:["Sobre una pieza de 37 × 37 cm, alinea la tira de 15 × 108 cm en tres lados, derecho con derecho.","Cose a 1 cm y remata con zigzag.","Añade la otra pieza de 37 × 37 cm.","Repite con el forro, dejando un hueco en un lateral para girar el bolso."],cap:"Página 1 · cuerpo del bolso"},
 {t:"Hacemos las asas",items:["Dobla cada tira por la mitad, con el derecho hacia dentro.","Cose el lado largo y un lado corto.","Gira, plancha y haz un pespunte de carga en los dos lados largos.","Marca el centro de la pieza y sitúa las asas a 5 cm a cada lado del centro."],cap:"Página 2 · asas"},
 {t:"Montamos el bolso",items:["Mete el bolso exterior dentro del interior, con los derechos enfrentados.","Haz coincidir las costuras y cose todo el contorno superior a 1 cm.","Gira por el hueco del forro y ciérralo con punto invisible.","Plancha y haz un pespunte de carga en todo el contorno superior."],cap:"Página 2–3 · montaje"}]},
en:{title:"Basic bag",materials:[["Lining","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Outer","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Handles","2 strips · 37 × 8 cm"]],steps:[
 {t:"Shape the two bags",items:["On one 37 × 37 cm piece, align the 15 × 108 cm strip along three sides, right sides together.","Sew at 1 cm and finish with a zigzag.","Add the other 37 × 37 cm piece.","Repeat with the lining, leaving a gap in one side to turn the bag."],cap:"Page 1 · bag body"},
 {t:"Make the handles",items:["Fold each strip in half, right side inside.","Sew the long side and one short side.","Turn, press and topstitch both long sides.","Mark the centre of the piece and place the handles 5 cm either side of it."],cap:"Page 2 · handles"},
 {t:"Assemble the bag",items:["Put the outer bag inside the lining bag, right sides facing.","Match the seams and sew all around the top at 1 cm.","Turn through the gap in the lining and close it with a slip stitch.","Press and topstitch all around the top."],cap:"Page 2–3 · assembly"}]},
de:{title:"Basic-Tasche",materials:[["Futter","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Aussenstoff","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Henkel","2 Streifen · 37 × 8 cm"]],steps:[
 {t:"Die beiden Taschen formen",items:["Lege den Streifen 15 × 108 cm rechts auf rechts an drei Seiten eines 37 × 37 cm Teils an.","Nähe bei 1 cm und versäubere mit Zickzack.","Setze das zweite 37 × 37 cm Teil an.","Wiederhole das mit dem Futter und lass an einer Seite eine Wendeöffnung."],cap:"Seite 1 · Taschenkörper"},
 {t:"Henkel nähen",items:["Falte jeden Streifen zur Hälfte, rechte Seite innen.","Nähe die lange Seite und eine kurze Seite.","Wende, bügle und steppe beide langen Seiten ab.","Markiere die Mitte des Teils und setze die Henkel 5 cm links und rechts davon."],cap:"Seite 2 · Henkel"},
 {t:"Tasche zusammensetzen",items:["Stecke die Aussentasche rechts auf rechts in die Futtertasche.","Lege die Nähte aufeinander und nähe die Oberkante rundum bei 1 cm.","Wende durch die Futteröffnung und schliesse sie mit dem Matratzenstich.","Bügle und steppe die Oberkante rundum ab."],cap:"Seite 2–3 · Montage"}]},
fr:{title:"Sac de base",materials:[["Doublure","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Extérieur","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Anses","2 bandes · 37 × 8 cm"]],steps:[
 {t:"Former les deux sacs",items:["Sur une pièce de 37 × 37 cm, aligne la bande de 15 × 108 cm sur trois côtés, endroit contre endroit.","Couds à 1 cm et surfile au zigzag.","Ajoute l’autre pièce de 37 × 37 cm.","Répète avec la doublure en laissant une ouverture sur un côté pour retourner."],cap:"Page 1 · corps du sac"},
 {t:"Faire les anses",items:["Plie chaque bande en deux, endroit à l’intérieur.","Couds le grand côté et un petit côté.","Retourne, repasse et surpique les deux grands côtés.","Marque le centre de la pièce et place les anses à 5 cm de chaque côté du centre."],cap:"Page 2 · anses"},
 {t:"Monter le sac",items:["Glisse le sac extérieur dans le sac doublure, endroit contre endroit.","Fais coïncider les coutures et couds tout le tour du haut à 1 cm.","Retourne par l’ouverture de la doublure et referme-la au point invisible.","Repasse et surpique tout le tour du haut."],cap:"Page 2–3 · montage"}]},
it:{title:"Borsa base",materials:[["Fodera","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Esterno","2 × 37 × 37 cm · 1 × 15 × 108 cm"],["Manici","2 strisce · 37 × 8 cm"]],steps:[
 {t:"Diamo forma alle due borse",items:["Su un pezzo di 37 × 37 cm, allinea la striscia di 15 × 108 cm su tre lati, dritto contro dritto.","Cuci a 1 cm e rifinisci con zigzag.","Aggiungi l’altro pezzo di 37 × 37 cm.","Ripeti con la fodera lasciando un’apertura su un lato per rivoltare."],cap:"Pagina 1 · corpo della borsa"},
 {t:"Facciamo i manici",items:["Piega ogni striscia a metà, con il dritto all’interno.","Cuci il lato lungo e un lato corto.","Rivolta, stira e fai un’impuntura sui due lati lunghi.","Segna il centro del pezzo e posiziona i manici a 5 cm da ogni lato del centro."],cap:"Pagina 2 · manici"},
 {t:"Montiamo la borsa",items:["Infila la borsa esterna in quella interna, dritto contro dritto.","Fai combaciare le cuciture e cuci tutto il bordo superiore a 1 cm.","Rivolta dall’apertura della fodera e chiudila con punto invisibile.","Stira e fai un’impuntura su tutto il bordo superiore."],cap:"Pagina 2–3 · montaggio"}]}
}};

GUIDES.lunch = {badge:"KIT 07",hours:2.5,imgs:[1,2,3,4],L:{
ca:{title:"Bossa per carmanyola",materials:[["Interior","2 × 47 × 35 cm"],["Exterior","2 × 47 × 35 cm"],["Estabilitzador","2 × 47 × 35 cm"],["Tancament","2 × 47 × 36 cm"],["Cinta de motxilla","2 m · cotó"],["Cordó","2 m"]],steps:[
 {t:"Comencem fent la bossa",items:["Per a l’exterior, encara les dues teles exteriors cara bonica amb cara bonica i posa una peça d’estabilitzador a cada costat.","Cus el conjunt a 1 cm segons la forma indicada al dibuix, deixant la part superior oberta.","Per al folre, encara les teles interiors i cus de la mateixa manera.","Deixa un forat d’uns 15 cm al folre per poder girar més endavant."],cap:"Pàgines 1–2 · exterior i folre"},
 {t:"Cosim la tela de tancament",items:["Encara les dues peces de tancament i cus només els laterals.","Doblega per la meitat al llarg i planxa, deixant la cara bonica a l’exterior.","Fes els repunts indicats per crear els canals del cordó.","Obre una petita entrada lateral, passa el cordó i deixa dues puntes per cada costat."],cap:"Pàgina 2 · tancament"},
 {t:"Preparem les nanses",items:["Talla la cinta en 3 peces: 2 de 30 cm i 1 d’1 m.","Col·loca les peces seguint el dibuix de muntatge.","Centra la nansa llarga i reparteix les curtes de forma simètrica."],cap:"Pàgina 3 · nanses"},
 {t:"Muntatge final",items:["Afegeix la peça de tancament a sobre de la bossa exterior.","Posa el folre dins del conjunt amb les cares boniques encarades.","Cus tot el contorn superior a 1 cm.","Gira pel forat del folre, tanca’l i fes un repunt final a la part superior."],cap:"Pàgina 3 · muntatge final"}]},
es:{title:"Bolsa para fiambrera",materials:[["Interior","2 × 47 × 35 cm"],["Exterior","2 × 47 × 35 cm"],["Estabilizador","2 × 47 × 35 cm"],["Cierre","2 × 47 × 36 cm"],["Cinta de mochila","2 m · algodón"],["Cordón","2 m"]],steps:[
 {t:"Empezamos por la bolsa",items:["Para el exterior, enfrenta las dos telas exteriores derecho con derecho y pon una pieza de estabilizador a cada lado.","Cose el conjunto a 1 cm siguiendo la forma del dibujo, dejando la parte superior abierta.","Para el forro, enfrenta las telas interiores y cose igual.","Deja un hueco de unos 15 cm en el forro para poder girar más adelante."],cap:"Páginas 1–2 · exterior y forro"},
 {t:"Cosemos la tela de cierre",items:["Enfrenta las dos piezas de cierre y cose solo los laterales.","Dobla por la mitad a lo largo y plancha, dejando el derecho hacia fuera.","Haz los pespuntes indicados para crear los canales del cordón.","Abre una pequeña entrada lateral, pasa el cordón y deja dos puntas por cada lado."],cap:"Página 2 · cierre"},
 {t:"Preparamos las asas",items:["Corta la cinta en 3 piezas: 2 de 30 cm y 1 de 1 m.","Coloca las piezas siguiendo el dibujo de montaje.","Centra el asa larga y reparte las cortas de forma simétrica."],cap:"Página 3 · asas"},
 {t:"Montaje final",items:["Añade la pieza de cierre encima de la bolsa exterior.","Mete el forro dentro del conjunto con los derechos enfrentados.","Cose todo el contorno superior a 1 cm.","Gira por el hueco del forro, ciérralo y haz un pespunte final en la parte superior."],cap:"Página 3 · montaje final"}]},
en:{title:"Lunch bag",materials:[["Lining","2 × 47 × 35 cm"],["Outer","2 × 47 × 35 cm"],["Stabiliser","2 × 47 × 35 cm"],["Closure","2 × 47 × 36 cm"],["Webbing","2 m · cotton"],["Cord","2 m"]],steps:[
 {t:"Start with the bag",items:["For the outer, put the two outer fabrics right sides together with a piece of stabiliser on each side.","Sew the set at 1 cm following the shape in the drawing, leaving the top open.","For the lining, face the inner fabrics and sew the same way.","Leave a gap of about 15 cm in the lining so you can turn it later."],cap:"Pages 1–2 · outer and lining"},
 {t:"Sew the closure fabric",items:["Face the two closure pieces and sew only the sides.","Fold in half lengthwise and press, right side out.","Sew the lines shown to create the cord channels.","Open a small side entry, thread the cord and leave two ends on each side."],cap:"Page 2 · closure"},
 {t:"Prepare the straps",items:["Cut the webbing into 3 pieces: 2 of 30 cm and 1 of 1 m.","Place the pieces following the assembly drawing.","Centre the long strap and space the short ones symmetrically."],cap:"Page 3 · straps"},
 {t:"Final assembly",items:["Add the closure piece on top of the outer bag.","Put the lining inside the set, right sides facing.","Sew all around the top at 1 cm.","Turn through the gap in the lining, close it and topstitch the top."],cap:"Page 3 · final assembly"}]},
de:{title:"Znünitasche",materials:[["Futter","2 × 47 × 35 cm"],["Aussenstoff","2 × 47 × 35 cm"],["Stabilisator","2 × 47 × 35 cm"],["Verschluss","2 × 47 × 36 cm"],["Gurtband","2 m · Baumwolle"],["Kordel","2 m"]],steps:[
 {t:"Zuerst die Tasche",items:["Für aussen die beiden Aussenstoffe rechts auf rechts legen und je ein Stück Stabilisator auf beide Seiten geben.","Das Paket bei 1 cm der Form in der Zeichnung folgend nähen, die Oberkante bleibt offen.","Für das Futter die Innenstoffe aufeinanderlegen und gleich nähen.","Im Futter eine Wendeöffnung von etwa 15 cm lassen."],cap:"Seiten 1–2 · Aussen und Futter"},
 {t:"Verschlussstoff nähen",items:["Die beiden Verschlussteile aufeinanderlegen und nur die Seiten nähen.","Der Länge nach zur Hälfte falten und bügeln, rechte Seite aussen.","Die eingezeichneten Nähte steppen, sie bilden die Kordelkanäle.","Seitlich eine kleine Öffnung machen, die Kordel einziehen und je zwei Enden pro Seite lassen."],cap:"Seite 2 · Verschluss"},
 {t:"Träger vorbereiten",items:["Das Gurtband in 3 Stücke schneiden: 2 × 30 cm und 1 × 1 m.","Die Stücke nach der Montagezeichnung platzieren.","Den langen Träger zentrieren und die kurzen symmetrisch verteilen."],cap:"Seite 3 · Träger"},
 {t:"Endmontage",items:["Das Verschlussteil auf die Aussentasche setzen.","Das Futter rechts auf rechts in das Paket stecken.","Die Oberkante rundum bei 1 cm nähen.","Durch die Futteröffnung wenden, schliessen und die Oberkante absteppen."],cap:"Seite 3 · Endmontage"}]},
fr:{title:"Sac à goûter",materials:[["Doublure","2 × 47 × 35 cm"],["Extérieur","2 × 47 × 35 cm"],["Stabilisateur","2 × 47 × 35 cm"],["Fermeture","2 × 47 × 36 cm"],["Sangle","2 m · coton"],["Cordon","2 m"]],steps:[
 {t:"On commence par le sac",items:["Pour l’extérieur, place les deux tissus extérieurs endroit contre endroit avec une pièce de stabilisateur de chaque côté.","Couds l’ensemble à 1 cm en suivant la forme du dessin, en laissant le haut ouvert.","Pour la doublure, superpose les tissus intérieurs et couds de la même façon.","Laisse une ouverture d’environ 15 cm dans la doublure pour retourner plus tard."],cap:"Pages 1–2 · extérieur et doublure"},
 {t:"Coudre le tissu de fermeture",items:["Superpose les deux pièces de fermeture et ne couds que les côtés.","Plie en deux dans la longueur et repasse, endroit à l’extérieur.","Fais les surpiqûres indiquées pour créer les coulisses du cordon.","Ouvre une petite entrée latérale, passe le cordon et laisse deux extrémités de chaque côté."],cap:"Page 2 · fermeture"},
 {t:"Préparer les anses",items:["Coupe la sangle en 3 : 2 de 30 cm et 1 de 1 m.","Place les morceaux selon le dessin de montage.","Centre l’anse longue et répartis les courtes symétriquement."],cap:"Page 3 · anses"},
 {t:"Montage final",items:["Ajoute la pièce de fermeture sur le sac extérieur.","Glisse la doublure dans l’ensemble, endroit contre endroit.","Couds tout le tour du haut à 1 cm.","Retourne par l’ouverture de la doublure, referme-la et surpique le haut."],cap:"Page 3 · montage final"}]},
it:{title:"Porta-merenda",materials:[["Fodera","2 × 47 × 35 cm"],["Esterno","2 × 47 × 35 cm"],["Stabilizzatore","2 × 47 × 35 cm"],["Chiusura","2 × 47 × 36 cm"],["Fettuccia","2 m · cotone"],["Cordoncino","2 m"]],steps:[
 {t:"Iniziamo dalla borsa",items:["Per l’esterno, affronta i due tessuti esterni dritto contro dritto e metti un pezzo di stabilizzatore per lato.","Cuci l’insieme a 1 cm seguendo la forma del disegno, lasciando aperto il bordo superiore.","Per la fodera, affronta i tessuti interni e cuci allo stesso modo.","Lascia un’apertura di circa 15 cm nella fodera per rivoltare più avanti."],cap:"Pagine 1–2 · esterno e fodera"},
 {t:"Cuciamo il tessuto di chiusura",items:["Affronta i due pezzi di chiusura e cuci solo i lati.","Piega a metà per il lungo e stira, con il dritto all’esterno.","Fai le impunture indicate per creare i canali del cordoncino.","Apri una piccola entrata laterale, infila il cordoncino e lascia due capi per lato."],cap:"Pagina 2 · chiusura"},
 {t:"Prepariamo i manici",items:["Taglia la fettuccia in 3 pezzi: 2 da 30 cm e 1 da 1 m.","Posiziona i pezzi seguendo il disegno di montaggio.","Centra il manico lungo e distribuisci i corti in modo simmetrico."],cap:"Pagina 3 · manici"},
 {t:"Montaggio finale",items:["Aggiungi il pezzo di chiusura sopra la borsa esterna.","Metti la fodera dentro l’insieme, dritto contro dritto.","Cuci tutto il bordo superiore a 1 cm.","Rivolta dall’apertura della fodera, chiudila e fai un’impuntura finale sul bordo."],cap:"Pagina 3 · montaggio finale"}]}
}};
